teur /app/dist/ /usr/share/nginx/html/
RUN cd /usr/share/nginx/html && \
    mv */browser/* . || \
    mv */* . || \
    echo "Files already in root"

# Config Nginx pour les Single Page Apps
RUN printf "server { \n\
    listen 80; \n\
    location / { \n\
        root /usr/share/nginx/html; \n\
        index index.html index.htm; \n\
        try_files \$uri \$uri/ /index.html; \n\
    } \n\
}" > /etc/nginx/conf.d/default.conf

EXPOSE 80
