spring.application.name=moneywise-backend

# MariaDB
# MariaDB (On utilise les noms définis dans le compose)
spring.datasource.url=jdbc:mariadb://moneywise-db:3306/moneywise
spring.datasource.username=moneywise
spring.datasource.password=MoneywisePass123!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Server
server.port=8080

# JWT
jwt.secret=MoneyWise_Super_Secret_Key_2026_Secure_256bits_JWT_Token
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost

# Logging
logging.level.com.moneywise=INFO
